export const FETCH_COVID_RECORDS_START = "FETCH_COVID_RECORDS_START";
export const FETCH_COVID_RECORDS_SUCCESS = "FETCH_COVID_RECORDS_SUCCESS";
export const FETCH_COVID_RECORDS_FAILED = "FETCH_COVID_RECORDS_FAILED";
export const CLEAR_IMAGE_STATE = "CLEAR_IMAGE_STATE";
