export const FETCH_COVID_RECORDS_START = "FETCH_COVID_RECORDS_START";
export const FETCH_COVID_RECORDS_SUCCESS = "FETCH_COVID_RECORDS_SUCCESS";
export const FETCH_COVID_RECORDS_FAILED = "FETCH_COVID_RECORDS_FAILED";
export const FETCH_HOSPITAL_BEDS_START = "FETCH_HOSPITAL_BEDS_START";
export const FETCH_HOSPITAL_BEDS_SUCCESS = "FETCH_HOSPITAL_BEDS_SUCCESS";
export const FETCH_HOSPITAL_BEDS_FAILED = "FETCH_HOSPITAL_BEDS_FAILED";

